sudo: required
services:
  - docker

before_install:
  - docker build -t max-kuzmenko/docker-frontend -f Dockerfile.test  .

script:
  - docker run max-kuzmenko/docker-frontend

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-frontend-eu"
  env: "DockerFrontendEu-env"
  bucket_name: "elasticbeanstalk-eu-north-1-144940371936"
  bucket_path: "docker-frontend-eu"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: master
